### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by maartenverbandt** [meco-group/ProjectEagle#3]
Possible memory leak using malloc in communicator.cpp: https://github.com/meco-group/ProjectEagle/blob/master/src/communicator.cpp#L318

**Comment by rubenvanparys** [comment]
Indeed. Memory for received data should be allocated by user. Another leak is situated [here](https://github.com/meco-group/ProjectEagle/blob/master/src/communicator.cpp#L294). This is easily resolved by freeing after the `zmsg_pushmem` (I assume this function _copies_ data).

**Comment by rubenvanparys** [comment]
No `malloc`'s left in `unpack()`. The user is responsible for allocating memory for its rcv data (vector).
